spring:
  datasource:
    url: jdbc:mysql://localhost:3306/vmsdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Taipei
    username: root
    password: root+123

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: info
    com.svm.backend: info